---
driver:
  name: vagrant
  vm_hostname: verdaccio-vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-18.04
- name: centos-7
- name: centos-8
##########################################################################
# See <https://github.com/test-kitchen/kitchen-ec2> for more documentation
# on kitchen-ec2
##########################################################################
#- name: amazon-2018.03
#  driver:
#    name: ec2

suites:
- name: default
  run_list:
    - recipe[verdaccio]
  attributes:
    verdaccio:
      listen: :4873
