name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:slim
    steps:
    - uses: actions/checkout@v2
    - name: Check style
      run: |
        apt -qq update && apt install -qq make
        bundle install
        bundle exec rake style

  # test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: chef/chefdk
  #   steps:
  #   - uses: actions/checkout@v2
  #     run: kitchen
